// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s17624_APBD_KolokwiumPoprawa.Models;

namespace s17624_APBD_KolokwiumPoprawa.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20200704182706_addedFirefighterAction")]
    partial class addedFirefighterAction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("s17624_APBD_KolokwiumPoprawa.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NeedSpecialEquipment")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("s17624_APBD_KolokwiumPoprawa.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialEquipment")
                        .HasColumnType("int");

                    b.HasKey("IdFireTruck");

                    b.ToTable("FireTrucks");
                });

            modelBuilder.Entity("s17624_APBD_KolokwiumPoprawa.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdFirefighter");

                    b.ToTable("Firefighters");
                });

            modelBuilder.Entity("s17624_APBD_KolokwiumPoprawa.Models.FirefighterAction", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int?>("FirefighterIdFirefighter")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "IdFirefighter");

                    b.HasIndex("FirefighterIdFirefighter");

                    b.ToTable("FirefighterActions");
                });

            modelBuilder.Entity("s17624_APBD_KolokwiumPoprawa.Models.FirefighterAction", b =>
                {
                    b.HasOne("s17624_APBD_KolokwiumPoprawa.Models.Firefighter", "Firefighter")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("FirefighterIdFirefighter");

                    b.HasOne("s17624_APBD_KolokwiumPoprawa.Models.Action", "Action")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
